title: Severson Group Knowledge Base
theme: minima
#theme: jekyll-theme-slate
author: Michael Mayberry
email: mayberry2@wisc.edu
description: > # this means to ignore newlines until "baseurl:"
  
show_excerpts: true # set to false to remove excerpts on the homepag
